name: track item price

on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  scheduled-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          node-version: "16"
      - run: npm install
      - run: node ./functions/trackPrice.js
